#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DTG_Ordering_System.Resource", IsApplication=true)]

namespace DTG_Ordering_System
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_up = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000e
			public const int addNewItem = 2131099662;
			
			// aapt resource value: 0x7f060001
			public const int addOrder = 2131099649;
			
			// aapt resource value: 0x7f06000f
			public const int button2 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int button3 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int button4 = 2131099665;
			
			// aapt resource value: 0x7f060000
			public const int categoriesListView = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int deleteDB = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int deliveryDate = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int editDate = 2131099659;
			
			// aapt resource value: 0x7f06001b
			public const int hasSent = 2131099675;
			
			// aapt resource value: 0x7f060004
			public const int itemListView = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int itemName = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int itemQuantity = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int itemUnit = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout1 = 2131099653;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout2 = 2131099661;
			
			// aapt resource value: 0x7f060002
			public const int loadDB = 2131099650;
			
			// aapt resource value: 0x7f060016
			public const int logOutButton = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int orderAdd = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int orderDate = 2131099674;
			
			// aapt resource value: 0x7f06001d
			public const int orderDelete = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int orderEdit = 2131099676;
			
			// aapt resource value: 0x7f060015
			public const int orderListView = 2131099669;
			
			// aapt resource value: 0x7f060019
			public const int orderNumber = 2131099673;
			
			// aapt resource value: 0x7f060014
			public const int pickerCancel = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int pickerOK = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int quantityPicker = 2131099666;
			
			// aapt resource value: 0x7f06000c
			public const int selectedItemsListView = 2131099660;
			
			// aapt resource value: 0x7f060017
			public const int syncButton = 2131099671;
			
			// aapt resource value: 0x7f060008
			public const int textView1 = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int categoryList = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int databaseScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int itemList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int itemListCustomRow = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int newOrder = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int newOrderCustomRow = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int numberPickerFragment = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int orderList = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int orderListCustomRow = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
